In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Pandas DF\product_inventory.csv")

In [3]:
df

,ProductID,ProductName,Category,StockQuantity,Supplier,WarehouseLocation,UnitCost
0,2001,Laptop,Furniture,187,PrimeTech,B2,326
1,2002,Monitor,Electronics,160,PrimeTech,A1,553
2,2003,Chair,Electronics,168,OfficeHub,C3,441
3,2004,Desk,Electronics,51,PrimeTech,A1,184
4,2005,Phone,Furniture,108,PrimeTech,A1,244
5,2006,Monitor,Furniture,16,GlobalSupply,B2,450
6,2007,Monitor,Electronics,153,PrimeTech,D4,689
7,2008,Tablet,Furniture,99,TechSource,B2,82
8,2009,Laptop,Electronics,121,PrimeTech,B2,737
9,2010,Laptop,Electronics,69,PrimeTech,B2,509
10,2011,Desk,Furniture,122,OfficeHub,B2,519
11,2012,Tablet,Furniture,11,TechSource,C3,424
12,2013,Monitor,Electronics,138,PrimeTech,D4,71
13,2014,Chair,Furniture,57,PrimeTech,A1,799
14,2015,Tablet,Furniture,149,GlobalSupply,A1,719
15,2016,Desk,Electronics,46,PrimeTech,D4,87
16,2017,Desk,Electronics,169,PrimeTech,A1,279
17,2018,Tablet,Furniture,18,GlobalSupply,D4,414
18,2019,Desk,Electronics,108,OfficeHub,A1,612
19,2020,Tablet,Electronics,156,PrimeTech,B2,487

In [4]:
import os

In [5]:
print(os.listdir())

['.ipynb_checkpoints', 'my_file.csv', 'notebook.ipynb', 'orders.csv', 'task.ipynb']

In [6]:
print(os.getcwd())

C:\Users\DELL\Documents\Python Tutorial Playground\Notebook\Pandas

In [7]:
df.columns

Index(['ProductID', 'ProductName', 'Category', 'StockQuantity', 'Supplier',
       'WarehouseLocation', 'UnitCost'],
      dtype='object')

In [8]:
# Data Manipulation And Transformation

# filter low stock quantity that is less than 50

df[df["StockQuantity"] < 50]

,ProductID,ProductName,Category,StockQuantity,Supplier,WarehouseLocation,UnitCost
5,2006,Monitor,Furniture,16,GlobalSupply,B2,450
11,2012,Tablet,Furniture,11,TechSource,C3,424
15,2016,Desk,Electronics,46,PrimeTech,D4,87
17,2018,Tablet,Furniture,18,GlobalSupply,D4,414

In [23]:
#df[["ProductName", "StockQuantity"]]
df.loc[df["ProductName"] == "Monitor"]

,ProductID,ProductName,Category,StockQuantity,Supplier,WarehouseLocation,UnitCost
1,2002,Monitor,Electronics,160,PrimeTech,A1,553
5,2006,Monitor,Furniture,16,GlobalSupply,B2,450
6,2007,Monitor,Electronics,153,PrimeTech,D4,689
12,2013,Monitor,Electronics,138,PrimeTech,D4,71

In [29]:
# Rename Column unitCost to Unite Cost
df.rename(columns = {"UnitCost": "Unit_Cost", "ProductID": "Product_ID", "ProductName": "Product_Name", "StockQuantity": "Stock_Quantity", "WarehouseLocation": "Warehouse_Location"}, inplace = True)

In [33]:
# create a new column called inventory

df["Inventory_Count"] = df["Stock_Quantity"] * df["Unit_Cost"]

In [37]:
df.drop(columns =["Inventory"], inplace = True)

In [38]:
df

,Product_ID,Product_Name,Category,Stock_Quantity,Supplier,Warehouse_Location,Unit_Cost,Inventory_Count
0,2001,Laptop,Furniture,187,PrimeTech,B2,326,60962
1,2002,Monitor,Electronics,160,PrimeTech,A1,553,88480
2,2003,Chair,Electronics,168,OfficeHub,C3,441,74088
3,2004,Desk,Electronics,51,PrimeTech,A1,184,9384
4,2005,Phone,Furniture,108,PrimeTech,A1,244,26352
5,2006,Monitor,Furniture,16,GlobalSupply,B2,450,7200
6,2007,Monitor,Electronics,153,PrimeTech,D4,689,105417
7,2008,Tablet,Furniture,99,TechSource,B2,82,8118
8,2009,Laptop,Electronics,121,PrimeTech,B2,737,89177
9,2010,Laptop,Electronics,69,PrimeTech,B2,509,35121
10,2011,Desk,Furniture,122,OfficeHub,B2,519,63318
11,2012,Tablet,Furniture,11,TechSource,C3,424,4664
12,2013,Monitor,Electronics,138,PrimeTech,D4,71,9798
13,2014,Chair,Furniture,57,PrimeTech,A1,799,45543
14,2015,Tablet,Furniture,149,GlobalSupply,A1,719,107131
15,2016,Desk,Electronics,46,PrimeTech,D4,87,4002
16,2017,Desk,Electronics,169,PrimeTech,A1,279,47151
17,2018,Tablet,Furniture,18,GlobalSupply,D4,414,7452
18,2019,Desk,Electronics,108,OfficeHub,A1,612,66096
19,2020,Tablet,Electronics,156,PrimeTech,B2,487,75972